In [ ]:
import numpy as np
np.__version__

In [ ]:
%%time
l = [[1,2,3],[4,5,6]]
a = np.array(l)
a.shape = (6,1)
print(a)
print(a.shape)
print(a.size)
print(type(a))

In [ ]:
b =  np.resize(a,(1,9))
print(b)

### Arange function

In [ ]:
x = np.arange(10,20,2)
print(x)
print(x.ndim)
x = np.arange(18).reshape(3,3,2)
# print(x)
# print(x.ndim)
print(x.itemsize)
a = np.array([1,2,3],dtype=np.uint16)
print(a.itemsize)
a = np.array([1,2,3],dtype=np.float32)
print(a.itemsize)

### Numpy creation routines
Order can be 'C' or 'F'
- C is for C-style row major form
- F is for Fortran-style column major form

In [ ]:
x = np.empty([2,6],dtype=int)
print(x)

### Numpy zeros
Use to create arrays with zeros

In [44]:
y = np.zeros((1,2),dtype=int, order='C')
print(y)

[[0 0]]


### Numpy asarray
Convert python list to numpy array and back

In [ ]:
l = [1,2,3]
a = np.array(l)
print(type(a))
b = list(a)
print(type(b))

### Numpy Linear Space
Range function gives step size
Linear space creates X number of equidistant values 

In [52]:
x = np.linspace(0,20,5)
print(x)
x = np.linspace(0,20,40)
print(x)

[ 0.  5. 10. 15. 20.]
40


### Numpy Axis
Axis is used to read the data in row or column order
- axis = 0 column wise
- axis = 1 row wise

In [ ]:
a = [[1,2],
     [5,4]]
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

### Matrix Operations
- add()


In [ ]:
a = np.array([[1,0],[0,1]])
b=np.array([3,1])
print(f'add= {np.add(a,b)}')
print(f'subtract= {np.subtract(a,b)}')
print(f'multiply= {np.multiply(a,b)}')
print(f'divide= {np.divide(a,b)}')
print(f'dot= {np.dot(a,b)}')

### Statistical functions

In [70]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(np.amin(a,axis=1)) # axis = 1 for row
print(np.amin(a,axis=0)) # axis = 0 for column
print(np.ptp(a))
print(np.ptp(a,axis=0))
print(np.ptp(a,axis=1))
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))


[3 3 2]
[2 4 3]
7
[6 3 6]
[4 5 7]
4.0
[3. 4. 5.]
[5. 4. 4.]
